name: log_app_wear
description: Wear OS wersion of Logger.

version: 1.1.4

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  flutter:
    sdk: flutter
  get_storage: ^2.0.3
  http: ^0.13.5
  wear: ^1.1.0
  scroll_snap_list: ^0.9.1
  chart_sparkline: ^1.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
